BTL_ASP_21/BTL_ASP/Models/LoaiHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiHang()
        {
            this.Hangs = new HashSet<Hang>();
        }
    
        public string LoaiHangID { get; set; }
        public string LoaiHangName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hang> Hangs { get; set; }
    }
}

BTL_ASP_21/BTL_ASP/Controllers/HangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BTL_ASP.Models;
using PagedList;
using PagedList.Mvc;

namespace BTL_ASP.Controllers
{
    public class HangController : Controller
    {
       
        DB_TikiNowEntities db = new DB_TikiNowEntities();

        // GET: HangMoi
        public PartialViewResult HangMoiPartial()
        {
            var lstSanPhamMoi = db.Hangs.Take(3).OrderByDescending(n => n.CreatedDate).ToList();
            return PartialView(lstSanPhamMoi);
        }
        public PartialViewResult HangMoiIndexPartial()
        {
            var lstSanPhamMoi = db.Hangs.Take(3).OrderByDescending(n => n.CreatedDate).ToList();
            return PartialView(lstSanPhamMoi);
        }
        public ViewResult XemChiTiet(string HangID)
        {
            Hang hang = db.Hangs.SingleOrDefault(n=>n.HangID==HangID);
            if (hang == null)
            {
                //trang baos looix
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.LoaiHangName = db.LoaiHangs.Single(n => n.LoaiHangID == hang.LoaiHangID).LoaiHangName;

            return View(hang);
        }
        public ActionResult HangSale(int? page)
        {
            //tao bien so sp tren trang
            int pageSize = 9;
            //bien so trang
            int pageNumber = (page ?? 1);
            return View(db.Hangs.Take(15).ToList().OrderBy(n => n.CreatedDate).ToPagedList(pageNumber, pageSize));
        }
    }
}

BTL_ASP_21/BTL_ASP/Controllers/LoaiHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BTL_ASP.Models;
namespace BTL_ASP.Controllers
{
    public class LoaiHangController : Controller
    {
        DB_TikiNowEntities db = new DB_TikiNowEntities();
       
        // GET: HangMoi
        public PartialViewResult LoaiHangPartial()
        {

            return PartialView(db.LoaiHangs.ToList());
        }
        public PartialViewResult LoaiHangMenuPartial()
        {
            return PartialView(db.LoaiHangs.ToList());
        }
        public PartialViewResult LoaiHangLocPartial()
        {
            return PartialView(db.LoaiHangs.ToList());
        }
        public ViewResult DanhMucLoaiHang()
        {
            return View(db.LoaiHangs.Take(5).ToList());
        }
        public ViewResult HangByLoaiHang(string LoaiHangID)
        {
            LoaiHang loaiHang = db.LoaiHangs.SingleOrDefault(n => n.LoaiHangID == LoaiHangID);
            if (loaiHang == null)
            {
                //trang baos looix
                Response.StatusCode = 404;
                return null;
            }
            List<Hang> lstHang = db.Hangs.Where(n => n.LoaiHangID == LoaiHangID).OrderBy(n => n.DonGia).ToList();
            if (lstHang.Count == 0)
            {
                ViewBag.Hang = "Khong co hang nao trong loai nay";
            }
            return View(lstHang);
        }
        public ViewResult HangByLoaiHangLoc(string LoaiHangID)
        {
            LoaiHang loaiHang = db.LoaiHangs.SingleOrDefault(n => n.LoaiHangID == LoaiHangID);
            if (loaiHang == null)
            {
                //trang baos looix
                Response.StatusCode = 404;
                return null;
            }
            List<Hang> lstHang = db.Hangs.Where(n => n.LoaiHangID == LoaiHangID).OrderBy(n => n.DonGia).ToList();
            if (lstHang.Count == 0)
            {
                ViewBag.Hang = "Khong co hang nao trong loai nay";
            }
            return View(lstHang);
        }
    }
}

BTL_ASP_21/BTL_ASP/Views/LoaiHang/HangByLoaiHang.cshtml
@using BTL_ASP.Models;
@model List<Hang>
@{
    ViewBag.Title = "HangByLoaiHang";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}
@ViewBag.Hang

@{
    foreach (var item in Model)
    {
        <div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
            <div class="block2">
                <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
                    <img src="@Url.Content(item.HangImage)" alt="IMG-PRODUCT">

                    <div class="block2-overlay trans-0-4">
                        <a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
                            <i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
                            <i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
                        </a>

                        <div class="block2-btn-addcart w-size1 trans-0-4">
                            <!-- Button -->
                            @using (Html.BeginForm("ThemGioHang", "GioHang", new { @hangID = item.HangID, @strUrl = Request.Url.ToString() }))
                            {
                                <input type="submit" value="Add to Cart" id="btnGioHang" class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" />
                            }
                        </div>
                    </div>
                </div>

                <div class="block2-txt p-t-20">
                    <a href="@Url.Action("XemChiTiet","Hang",new { @hangID=item.HangID})" class="block2-name dis-block s-text3 p-b-5">
                        @item.HangName
                    </a>

                    <span class="block2-price m-text6 p-r-5">
                        @item.DonGia
                    </span>
                </div>
            </div>
        </div>
    }
}

BTL_ASP_21/BTL_ASP/Views/LoaiHang/HangByLoaiHangLoc.cshtml
@using BTL_ASP.Models;
@model List<Hang>
@{
    ViewBag.Title = "HangByLoaiHangLoc";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
@ViewBag.Hang
<br /><br />
<div class="flex-sb-m flex-w p-b-35">

    <div class="flex-w">
        <div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10">
            <select class="selection-2" name="sorting">
                <option>Default Sorting</option>
                @Html.Action("LoaiHangLocPartial", "LoaiHang")
            </select>
        </div>
    </div>
</div>
<br /><br />
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên Hàng
        </th>
        <th>
            SKU
        </th>
        <th>
            Image
        </th>

        <th>
            Số Lượng
        </th>
        <th>
            Đơn Giá
        </th>
        <th>
            Loại Hàng
        </th>
        <th>
            Ngày Tạo
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HangName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SKU)
            </td>
            <td>
                <img src="@Url.Content(item.HangImage)" alt="IMG" style="width:60px; height:60px;" />

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoaiHang.LoaiHangName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { @HangID = item.HangID }) |
                @Html.ActionLink("Details", "Details", new { @HangID = item.HangID }) |
                @Html.ActionLink("Delete", "Delete", new { @HangID = item.HangID })
            </td>
        </tr>
    }

</table>

BTL_ASP_21/BTL_ASP/Views/LoaiHang/LoaiHangLocPartial.cshtml
@using BTL_ASP.Models;
@model List<LoaiHang>


    @{foreach (var item in Model)
        {
           
                <option>
                 <a href="@Url.Action("HangByLoaiHangLoc",new { @loaiHangID=item.LoaiHangID})" class="s-text13 active1">@item.LoaiHangName</a>
                </option>
        }

    }

BTL_ASP_21/BTL_ASP/Views/LoaiHang/LoaiHangMenuPartial.cshtml
@using BTL_ASP.Models;
@model List<LoaiHang>



    @{foreach (var item in Model)
        {
            <li>
                <a href="@Url.Action("HangByLoaiHang",new { @loaiHangID=item.LoaiHangID})">
                    @item.LoaiHangName
                </a>
            </li>
        }

    }
   

BTL_ASP_21/BTL_ASP/Views/LoaiHang/LoaiHangPartial.cshtml
@using BTL_ASP.Models;
@model List<LoaiHang>

<h4 class="m-text14 p-b-7">
    Danh mục loại hàng
</h4>

<ul class="p-b-54">
    @{foreach (var item in Model)
        {
            <li class="p-t-4">
                <a href="@Url.Action("HangByLoaiHang",new { @loaiHangID=item.LoaiHangID})" class="s-text13 active1">
                  
                        @item.LoaiHangName
                   
                   
                </a>
            </li>
        }
      
    }
</ul>