BTL_ASP_21/BTL_ASP/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BTL_ASP.Models;
using System.IO;
using PagedList;
using PagedList.Mvc;
using System.Linq.Expressions;
using System.Linq.Dynamic;
using System.Reflection;

namespace BTL_ASP.Controllers
{
    public class QuanLySanPhamController : Controller
    {
        DB_TikiNowEntities db = new DB_TikiNowEntities();
        // GET: QuanLySanPham
        public ActionResult IndexStart()
        {
            if (Session["TaiKhoan"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("DangNhap", "QuanTri");
            }
        }
        public ActionResult Index(int? size, int? page, string sortOrder)
        {
            if (Session["TaiKhoan"] != null)
            {
                ViewBag.LoaiHangID = new SelectList(db.LoaiHangs.ToList(), "LoaiHangID", "LoaiHangName");
                
                ViewBag.page = page;
              ViewBag.SoLuongSortParm = String.IsNullOrEmpty(sortOrder) ? "soluong_desc" : "";
                var hangs = from h in db.Hangs
                            select h;
             
                // 3. Thứ tự sắp xếp theo thuộc tính LinkName
                switch (sortOrder)
                {
                    // 3.1 Nếu biến sortOrder sắp giảm thì sắp giảm theo LinkName
                    case "soluong_desc":
                        hangs = hangs.OrderByDescending(s => s.SoLuong);
                        break;

                    // 3.2 Mặc định thì sẽ sắp tăng
                    case "":
                        hangs = hangs.OrderBy(s => s.SoLuong);
                        break;
                    default:
                        hangs = hangs.OrderBy(s => s.HangID);
                        break;
                }

                List<SelectListItem> items = new List<SelectListItem>();
                items.Add(new SelectListItem { Text = "5", Value = "5" });
                items.Add(new SelectListItem { Text = "10", Value = "10" });
                items.Add(new SelectListItem { Text = "20", Value = "20" });
                items.Add(new SelectListItem { Text = "25", Value = "25" });
                items.Add(new SelectListItem { Text = "50", Value = "50" });
                items.Add(new SelectListItem { Text = "100", Value = "100" });
                items.Add(new SelectListItem { Text = "200", Value = "200" });

                // 1.1. Giữ trạng thái kích thước trang được chọn trên DropDownList
                foreach (var item in items)
                {
                    if (item.Value == size.ToString()) item.Selected = true;
                }
                // 1.2. Tạo các biến ViewBag
                ViewBag.size = items; // ViewBag DropDownList
                ViewBag.currentSize = size; // tạo biến kích thước trang hiện tại
              
                    //phan trang
                    int pageNumber = (page ?? 1);
                int pageSize = (size ?? 5);
                return View(hangs.ToPagedList(pageNumber, pageSize));

            }
            else
            {
                return RedirectToAction("DangNhap", "QuanTri");
            }
        }
        #region IndexPage
        //public ActionResult Index(int ? size,int? page)
        //{
        //    if (Session["TaiKhoan"] != null)
        //    {
        //        List<SelectListItem> items = new List<SelectListItem>();
        //        items.Add(new SelectListItem { Text = "5", Value = "5" });
        //        items.Add(new SelectListItem { Text = "10", Value = "10" });
        //        items.Add(new SelectListItem { Text = "20", Value = "20" });
        //        items.Add(new SelectListItem { Text = "25", Value = "25" });
        //        items.Add(new SelectListItem { Text = "50", Value = "50" });
        //        items.Add(new SelectListItem { Text = "100", Value = "100" });
        //        items.Add(new SelectListItem { Text = "200", Value = "200" });

        //        // 1.1. Giữ trạng thái kích thước trang được chọn trên DropDownList
        //        foreach (var item in items)
        //        {
        //            if (item.Value == size.ToString()) item.Selected = true;
        //        }
        //        // 1.2. Tạo các biến ViewBag
        //        ViewBag.size = items; // ViewBag DropDownList
        //        ViewBag.currentSize = size; // tạo biến kích thước trang hiện tại

        //        //phan trang
        //        int pageNumber = (page ?? 1);
        //        int pageSize = (size ?? 5);
        //        return View(db.Hangs.OrderBy(n => n.HangName).ToPagedList(pageNumber, pageSize));

        //    }
        //    else
        //    {
        //        return RedirectToAction("DangNhap", "QuanTri");
        //    }
        //}
        #endregion
        #region index
        //public ActionResult Index(int? page)
        //{
        //    if (Session["TaiKhoan"] != null)
        //    {
        //        //phan trang
        //        int pageNumber = (page ?? 1);
        //        int pageSize = 5;
        //        return View(db.Hangs.OrderBy(n => n.HangName).ToPagedList(pageNumber, pageSize));

        //    }
        //    else
        //    {
        //        return RedirectToAction("DangNhap", "QuanTri");
        //    }
        //}
        #endregion
        #region filterMySim
        //public class HttpParamActionAttribute : ActionNameSelectorAttribute
        //{
        //    public override bool IsValidName(ControllerContext controllerContext, string actionName, MethodInfo methodInfo)
        //    {
        //        if (actionName.Equals(methodInfo.Name, StringComparison.InvariantCultureIgnoreCase))
        //            return true;

        //        var request = controllerContext.RequestContext.HttpContext.Request;
        //        return request[methodInfo.Name] != null;
        //    }
        //}
        //[HttpGet]
        //// GET: /Link/
        //public ActionResult Index(int? size, int? page, string sortProperty, string sortOrder)
        //{
        //    // 1. Tạo biến ViewBag gồm sortOrder, searchValue, sortProperty và page
        //    if (sortOrder == "asc") ViewBag.sortOrder = "desc";
        //    if (sortOrder == "desc") ViewBag.sortOrder = "";
        //    if (sortOrder == "") ViewBag.sortOrder = "asc";

        //    ViewBag.sortProperty = sortProperty;
        //    ViewBag.page = page;

        //    // 2. Tạo danh sách chọn số trang
        //    List<SelectListItem> items = new List<SelectListItem>();
        //    items.Add(new SelectListItem { Text = "5", Value = "5" });
        //    items.Add(new SelectListItem { Text = "10", Value = "10" });
        //    items.Add(new SelectListItem { Text = "20", Value = "20" });
        //    items.Add(new SelectListItem { Text = "25", Value = "25" });
        //    items.Add(new SelectListItem { Text = "50", Value = "50" });
        //    items.Add(new SelectListItem { Text = "100", Value = "100" });
        //    items.Add(new SelectListItem { Text = "200", Value = "200" });

        //    // 2.1. Thiết lập số trang đang chọn vào danh sách List<SelectListItem> items
        //    foreach (var item in items)
        //    {
        //        if (item.Value == size.ToString()) item.Selected = true;
        //    }
        //    ViewBag.size = items;
        //    ViewBag.currentSize = size;

        //    // 3. Lấy tất cả tên thuộc tính của lớp Link (LinkID, LinkName, LinkURL,...)
        //    var properties = typeof(Hang).GetProperties();
        //    List<Tuple<string, bool, int>> list = new List<Tuple<string, bool, int>>();
        //    foreach (var item in properties)
        //    {
        //        int order = 999;
        //        var isVirtual = item.GetAccessors()[0].IsVirtual;
        //        if (item.Name == "HangID") order = 1;
        //        if (item.Name == "HangName") order = 2;
        //        if (item.Name == "SKU") order = 3;
        //        if (item.Name == "HangImage") order = 4;
        //        if (item.Name == "SoLuong") order = 5;
        //        if (item.Name == "DonGia") order = 6;
        //        if (item.Name == "LoaiHangID") order =7;
        //        if (item.Name == "CreatedDate") order = 8;

        //        if (item.Name == "MoTa") continue;
        //        if (item.Name == "ThuongHieuID") continue;// Không hiển thị cột này
        //        if (item.Name == "NhaCungCapID") continue;// Không hiển thị cột này
        //        Tuple<string, bool, int> t = new Tuple<string, bool, int>(item.Name, isVirtual, order);
        //        list.Add(t);
        //    }
        //    list = list.OrderBy(x => x.Item3).ToList();

        //    // 3.1. Tạo Heading sắp xếp cho các cột
        //    foreach (var item in list)
        //    {
        //        if (!item.Item2)
        //        {
        //            if (sortOrder == "desc" && sortProperty == item.Item1)
        //            {
        //                ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
        //                    ViewBag.sortOrder  + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-desc'></i></th></a></th>";
        //            }
        //            else if (sortOrder == "asc" && sortProperty == item.Item1)
        //            {
        //                ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
        //                    ViewBag.sortOrder +  "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-asc'></a></th>";
        //            }
        //            else
        //            {
        //                ViewBag.Headings += "<th><a href='?page=" + page + "&size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +

BTL_ASP_21/BTL_ASP/Views/QuanLySanPham/Create.cshtml
@model BTL_ASP.Models.Hang

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","QuanLySanPham",FormMethod.Post,new {@enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row-fluid sortable">
        <div class="box-content">

           <div class="form-horizontal">
           
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="control-group">
                <label class="control-label" for="date01">Mã hàng: </label>
                <div class="controls">
                    @Html.EditorFor(model => model.HangID, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="date01">Tên hàng:</label>
                <div class="controls">
                    @Html.EditorFor(model => model.HangName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HangName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.SKU, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    @Html.EditorFor(model => model.SKU, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SKU, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.HangImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    <input type="file" name="fileUpload" />
                    @ViewBag.ThongBao
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.LoaiHangID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    @Html.DropDownList("LoaiHangID")
                    @Html.ValidationMessageFor(model => model.LoaiHangID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.ThuongHieuID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    @Html.DropDownList("ThuongHieuID")
                    @Html.ValidationMessageFor(model => model.ThuongHieuID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.NhaCungCapID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    @Html.DropDownList("NhaCungCapID")
                    @Html.ValidationMessageFor(model => model.NhaCungCapID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="control-group">
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="controls">
                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
                
                <div class="controls">
                    <textarea name="MoTa" class="cleditor" id="textarea2" rows="3"></textarea>
                    @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-actions">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
        </div>
    </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

BTL_ASP_21/BTL_ASP/Views/QuanLySanPham/CreateHang.cshtml
@model BTL_ASP.Models.Hang

@{
    ViewBag.Title = "CreateHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<div class="row-fluid sortable">
    <div class="box-content">
        @using (Html.BeginForm("CreateHang", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
           
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.HangID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.EditorFor(model => model.HangID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HangID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.HangName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.EditorFor(model => model.HangName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HangName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.SKU, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.EditorFor(model => model.SKU, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SKU, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.HangImage, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        <input type="file" name="fileUpload" />
                        @ViewBag.ThongBao
                    </div>
                </div>

                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.LoaiHangID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.DropDownList("LoaiHangID")
                        @Html.ValidationMessageFor(model => model.LoaiHangID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.ThuongHieuID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.DropDownList("ThuongHieuID")
                        @Html.ValidationMessageFor(model => model.ThuongHieuID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.NhaCungCapID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.DropDownList("NhaCungCapID")
                        @Html.ValidationMessageFor(model => model.NhaCungCapID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10 sim">
                        <textarea name="MoTa" class="cleditor" id="textarea2" rows="3"></textarea>
                        @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 sim">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
</div>
    </div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
<style>
    .col-md-10.sim {
    margin-left: 200px;
}
</style>

BTL_ASP_21/BTL_ASP/Views/QuanLySanPham/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<BTL_ASP.Models.Hang>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<br />
<div class="row-fluid">
    <div class="span6">

    </div>
    <div class="span6">
        @using (Html.BeginForm("KetQuaTimKiem", "QuanLySanPham", FormMethod.Post))
        {
            <span> Search:</span>
            @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "s-text7 size6 p-l-23 p-r-50", @placeholder = "Search Products..." })
            <button class="flex-c-m size5 ab-r-m color2 color0-hov trans-0-4">
                <i class="halflings-icon search" aria-hidden="true"></i>
            </button>
        }

    </div>
</div>
@using (Html.BeginForm("Index", "QuanLySanPham", FormMethod.Get))
{
    <p>
        @Html.Hidden("page", (object)ViewBag.page)
        @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
        @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
        @Html.Hidden("size", (object)ViewBag.pageSize)
    </p>
}
   
    <p class="newitem">
        @Html.ActionLink("Thêm mới", "CreateHang")
    </p>
    <table class="table">
        <tr>
            <th>
              Tên Hàng
            </th>
            <th>
                SKU
            </th>
            <th>
                Image
            </th>

            <th>
                @Html.ActionLink("Số Lượng", "Index", new {size= ViewBag.currentSize,page = ViewBag.page, sortOrder = ViewBag.SoLuongSortParm })
            </th>
            <th>
                Đơn Giá
            </th>
            <th>
                Loại Hàng
            </th>
            <th>
                Ngày Tạo
            </th>
            <th></th>
        </tr>
       

        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.HangName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SKU)
                </td>
                <td>
                    <img src="@Url.Content(item.HangImage)" alt="IMG" style="width:60px; height:60px;" />

                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.SoLuong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonGia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoaiHang.LoaiHangName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { @HangID = item.HangID }) |
                    @Html.ActionLink("Details", "Details", new { @HangID = item.HangID }) |
                    @Html.ActionLink("Delete", "Delete", new { @HangID = item.HangID }, new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                </td>
            </tr>
        }

    </table>
<div style="clear:both;"></div>
<!-- Thêm mã phân trang -->
<br />

<div class="container pagetext">
    <div>
        @using (Html.BeginForm("Index", "QuanLySanPham", FormMethod.Get))
        {
            <p>
                Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
            </p>

        }
    </div>
    <div >
        Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    </div>
    <div class="page">

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, size = ViewBag.currentSize, sortOrder = ViewBag.SoLuongSortParm }))
    </div>
</div>

  
 <!-- Kết thúc -->
    <!--Tao link lien ket cac trang@model IEnumerable<BTL_ASP.Models.Hang>-->
   
 @*<div class="container pagetext">
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;
            <div class="page">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
            </div>
        </div>*@
    <style>
        .pagetext {
            text-align: center;
        }

        .page {
        }

            .page ul li {
                list-style: none;
                display: inline;
            }

            .page li {
                padding: 5px;
            }

        .newitem {
            width: 120px;
    height: 30px;
    background-color: deepskyblue;
    color: black;
    border: solid cornflowerblue;
    text-align: center;
    font-family: serif;
        }

            .newitem a {
                text-decoration: none;
                color: black;
                font-size: 20px;
            }
    </style>
    <script src="~/scripts/jquery-1.10.2.min.js"></script>
    <script>
        $("#dialog-confirm").dialog({
            autoOpen: false,
            resizable: false,
            width: 500,
            modal: true,
            buttons: {
                "Delete this item": function () {
                    $(this).dialog("close");
                },
                Cancel: function () {
                    $(this).dialog("close");
                }
            }
        });

        $("[data-dialog-confirm]").click(function (e) {
            e.preventDefault();
            var theHREF = $(this).attr("href");
            $("#dialog-confirm").dialog('option', 'buttons', {
                "Yes":
                function () {
                    $.get(theHREF, null, function () { refreshList() });
                    $(this).dialog("close");
                }, "No":
              function () { $(this).dialog("close"); }
            });
            $("#dialog-confirm").dialog("open");
        });
    </script>

BTL_ASP_21/BTL_ASP/Views/QuanLySanPham/KetQuaTimKiem.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<BTL_ASP.Models.Hang>

@{
    ViewBag.Title = "KetQuaTimKiem";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<br /><br />
<div class="row-fluid">
    <div class="span6">

    </div>
    <div class="span6">
        @using (Html.BeginForm("KetQuaTimKiem", "QuanLySanPham", FormMethod.Post))
        {
            <span> Search:</span>
            @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "s-text7 size6 p-l-23 p-r-50", @placeholder = "Search Products..." })
            <button class="flex-c-m size5 ab-r-m color2 color0-hov trans-0-4">
                <i class="halflings-icon search" aria-hidden="true"></i>
            </button>
        }

    </div>
</div>

@ViewBag.ThongBao
<br /><br />
<p class="newitem">
    @Html.ActionLink("Thêm mới", "CreateHang")
</p>
<table class="table">
    <tr>
        <th>
            Tên Hàng
        </th>
        <th>
            SKU
        </th>
        <th>
            Image
        </th>

        <th>
            Số Lượng
        </th>
        <th>
            Đơn Giá
        </th>
        <th>
            Loại Hàng
        </th>
        <th>
            Ngày Tạo
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HangName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SKU)
            </td>
            <td>
                <img src="@Url.Content(item.HangImage)" alt="IMG" style="width:60px; height:60px;" />

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoaiHang.LoaiHangName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { @HangID = item.HangID }) |
                @Html.ActionLink("Details", "Details", new { @HangID = item.HangID }) |
                @Html.ActionLink("Delete", "Delete", new { @HangID = item.HangID }, new { onclick = "return confirm('Are you sure you wish to delete this?');" })
            </td>
        </tr>
    }

</table>
<div style="clear:both;"></div>
<!--Tao link lien ket cac trang@model IEnumerable<BTL_ASP.Models.Hang>-->
<div class="container pagetext">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;
    <div class="page">
        @Html.PagedListPager(Model, page => Url.Action("KetQuaTimKiem", new { page = page, @tuKhoa = ViewBag.TuKhoa }))
    </div>
</div>
<style>
    .pagetext {
        text-align: center;
    }

    .page {
    }

        .page ul li {
            list-style: none;
            display: inline;
        }

        .page li {
            padding: 5px;
        }
         .newitem{
            width:120px; height:30px; background-color:deepskyblue; color:black
        }
        .newitem a{
            text-decoration:none;
            color:black;
            font-size:20px;
        }
</style>